#!/bin/bash
setx AUTH0_SECRET "MnRzwx/UwWdnUys4nP9tEyu0Mcn/8t8qKd1m+sz2i8mAqN9OMoTqoMPjbSVw4d7hKdsrLOIHkkLVdignXbQIiFz8FSYmoLs6bATIgjpar+Hu0yohxAXjZZKsGXVCX7JiNPb9SIuRMbBtfB80HfOPfdHzA5orJRGlbGQ5h6kftJVyLM+Rb9SxqYcYFWsXCr6IMJXPguttde4+SOcrG+EOoBjHpxtLY3Fm0Ku6fejiHpyrHxQvItdbkfmqKhFbcqbCPuqUCY9D0lHhSXlrD7LggCQSL74LNmB888TUrBImxsCkUPCGnjpkAmQTgauKsHrpNK8N0VIuBwLQ1fIWnPhiZg=="
setx AUTH0_BASE_URL "http://localhost:3000"
setx AUTH0_ISSUER_BASE_URL "https://dev-k3iu6ckt.us.auth0.com"
setx AUTH0_CLIENT_ID "ZDzsnQnAdHtwbLyPDS0yF9bKb9w9zu8P"
setx AUTH0_CLIENT_SECRET "6ciMOn66XT9HFNQmjwIelA-5-UjoAB1Yakx-UDhv5x4NkWBjmYVs-v2jGlDwwb4g"
setx AUTH0_AUDIENCE "http://localhost:5000"
setx AUTH0_SCOPE "openid profile email post:products patch:products delete:products"
setx BACKEND_URL "https://fullstack-capstone-backend.herokuapp.com"
setx FRONTEND_URL "https://fullstack-capstone-frontend.herokuapp.com"
echo "setup.sh script executed successfully!"