"""Minor changes

Revision ID: 54aa803173f7
Revises: eac52081900f
Create Date: 2022-07-05 21:36:14.718930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54aa803173f7'
down_revision = 'eac52081900f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'user_id')
    # ### end Alembic commands ###
